/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uni.sistemas.view;

import uni.sistemas.controller.OperacionesController;
import uni.sistemas.entity.Operaciones;
import uni.sistemas.model.OperacionesModel;

/**
 *
 * @author Dony
 */
public class OperacionesView extends javax.swing.JFrame {

    /**
     * Creates new form OperacionesView
     */
    public OperacionesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BtnSuma = new javax.swing.JButton();
        BtnRestar = new javax.swing.JButton();
        BtnDivision = new javax.swing.JButton();
        BtnMultiplicar = new javax.swing.JButton();
        TxtComparar = new javax.swing.JLabel();
        TxtN1 = new javax.swing.JTextField();
        TxtN2 = new javax.swing.JTextField();
        TxtInput = new javax.swing.JTextField();
        BtnLimpiar = new javax.swing.JButton();
        TxtResultado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnSalir = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OPERACIONES BASICAS");
        setBackground(new java.awt.Color(0, 0, 204));

        BtnSuma.setBackground(new java.awt.Color(0, 51, 204));
        BtnSuma.setForeground(new java.awt.Color(255, 255, 255));
        BtnSuma.setText("Sumar");
        BtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumaActionPerformed(evt);
            }
        });

        BtnRestar.setBackground(new java.awt.Color(0, 51, 204));
        BtnRestar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRestar.setText("Restar");
        BtnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestarActionPerformed(evt);
            }
        });

        BtnDivision.setBackground(new java.awt.Color(0, 0, 204));
        BtnDivision.setForeground(new java.awt.Color(255, 255, 255));
        BtnDivision.setText("Division");
        BtnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDivisionActionPerformed(evt);
            }
        });

        BtnMultiplicar.setBackground(new java.awt.Color(0, 51, 204));
        BtnMultiplicar.setForeground(new java.awt.Color(255, 255, 255));
        BtnMultiplicar.setText("Multiplicar");
        BtnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiplicarActionPerformed(evt);
            }
        });

        TxtComparar.setText("Ingresa ");

        TxtN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtN1ActionPerformed(evt);
            }
        });

        BtnLimpiar.setBackground(new java.awt.Color(0, 51, 204));
        BtnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setText(" Respuesta");

        BtnSalir.setBackground(new java.awt.Color(0, 51, 204));
        BtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BtnRestar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(16, 16, 16))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TxtComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TxtN2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addComponent(TxtInput)
                                .addComponent(TxtN1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BtnDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnMultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(TxtResultado)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSuma)
                    .addComponent(TxtN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMultiplicar))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRestar)
                    .addComponent(BtnDivision)
                    .addComponent(TxtN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtComparar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnSalir)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumaActionPerformed
        procesar(1);
        
    }//GEN-LAST:event_BtnSumaActionPerformed

    private void BtnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestarActionPerformed
        procesar(2);
    }//GEN-LAST:event_BtnRestarActionPerformed

    private void BtnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiplicarActionPerformed
        procesar(3);
    }//GEN-LAST:event_BtnMultiplicarActionPerformed

    private void BtnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDivisionActionPerformed
        procesar(4);
    }//GEN-LAST:event_BtnDivisionActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        procesar(5);
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        procesar(6);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void TxtN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacionesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacionesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacionesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacionesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperacionesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDivision;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnMultiplicar;
    private javax.swing.JButton BtnRestar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSuma;
    private javax.swing.JLabel TxtComparar;
    private javax.swing.JTextField TxtInput;
    private javax.swing.JTextField TxtN1;
    private javax.swing.JTextField TxtN2;
    private javax.swing.JTextField TxtResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
   OperacionesController obj = new OperacionesController();
   Operaciones ope;
   OperacionesModel om = new OperacionesModel();
   private void procesar(int opcion){
       switch(opcion){
           case 1:
               generarSuma();
               break;
           case 2:
               generarResta();
               break;
           case 3:
               generarMultiplicacion();
               break;
           case 4:
               generarDivision();
               break;
           case 5:
               limpiarCajas();
               break;
           case 6:
               dispose();
               
       }
   }
   private void generarSuma(){
       ope = new Operaciones();
       //asignar Valores
       ope.setN1(Double.parseDouble(TxtN1.getText()));
       ope.setN2(Double.parseDouble(TxtN2.getText()));
       ope.setInput(Double.parseDouble(TxtInput.getText()));  
       //ver resultado
       om.procesarSuma(ope);
       TxtResultado.setText(om.compararNum(ope.getSuma(),ope.getInput()));
   }
   private void generarResta(){
       ope = new Operaciones();
       //asignar Valores
       ope.setN1(Double.parseDouble(TxtN1.getText()));
       ope.setN2(Double.parseDouble(TxtN2.getText()));
       ope.setInput(Double.parseDouble(TxtInput.getText()));  
       //ver resultado
       om.procesarResta(ope);
       TxtResultado.setText(om.compararNum(ope.getRestado(), ope.getInput()));
   }
   private void generarMultiplicacion(){
       ope = new Operaciones();
       //asignar Valores
       ope.setN1(Double.parseDouble(TxtN1.getText()));
       ope.setN2(Double.parseDouble(TxtN2.getText()));
       ope.setInput(Double.parseDouble(TxtInput.getText()));  
       //ver resultado
       om.procesarMultiplicacion(ope);
       TxtResultado.setText(om.compararNum(ope.getMulti(), ope.getInput()));
   }
   private void generarDivision(){
       ope = new Operaciones();
       //asignar Valores
       ope.setN1(Double.parseDouble(TxtN1.getText()));
       ope.setN2(Double.parseDouble(TxtN2.getText()));
       ope.setInput(Double.parseDouble(TxtInput.getText()));  
       //ver resultado
       om.procesarDivision(ope);
       TxtResultado.setText(om.compararNum(ope.getDiv(), ope.getInput()));
   }
   private void limpiarCajas(){
       TxtN1.setText("");
       TxtN2.setText("");
       TxtInput.setText("");
       TxtResultado.setText("");
   }
}
